package Tk::Config;
require Exporter;
use base qw(Exporter);
$VERSION = '800.022';
$inc = '-I/usr/openwin/include';
$define = '';
$xlib = '-L/usr/openwin/lib';
$xinc = '-I/usr/openwin/include';
$gccopt = ' -Wall -Wno-implicit-int -Wno-comment -Wno-unused -D__USE_FIXED_PROTOTYPES__ -isystem /usr/openwin/include';
$win_arch = 'x';
@EXPORT = qw($VERSION $inc $define $xlib $xinc $gccopt $win_arch);
1;
